### PR TITLE
Fixed whitespace and semicolon mistakes.

### PR DESCRIPTION
**Pull request by wordempire**

### CODE REVIEW

**Comment by blacksph3re** [comment]
Could you actually do these changes on the dev branch? I think we might have some merge conflicts when we want to merge the dev back to master and I would rather have them now.

**Comment by linuxbandit** [comment]
please check this out

 http://nvie.com/posts/a-successful-git-branching-model/

**Comment by wordempire** [comment]
Lots of work still. We should properly format the code the first time
around.

**Comment by linuxbandit** [comment]
format?

**Comment by wordempire** [comment]
No longer needed because of pr #5

**Pull request closed without merging**
