### PR TITLE
(Impr) Dockerfile now is the docker way

### PR DESCRIPTION
**Pull request by linuxbandit**
The source files are copied on build time and not mounted.
This is the way the Dockerfiles should be written. Unfortunately
due to scopes, the Dockerfile cannot be inside docker, because
the COPY operation does not go above (..) the Dockerfile position.
Alternative to this could be to 'RUN git clone [....]' but this
approach is too rigid: in the way proposed, the files can still
be modified and the image rebuilt.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
then we can delete the old Dockerfile, right?

**Comment by serge1peshcoff** [comment]
I also wonder why one of 2 checks fails

**Comment by linuxbandit** [comment]
one of the two fails because I pushed to AEGEE first instead of my repo, so travis is confused

Good idea about excluding the .git folder! Yes, I have just to add a .dockerignore file. I will do and push right away

**Comment by serge1peshcoff** [comment]
also, for oms-frontend, sometimes it fails because node_modules/ in my folder was build for Mac (the host system), not for Linux (the container guest system). we currently don't have such problems with oms-events, but who knows. that's why I also suggest adding it.

**Comment by linuxbandit** [comment]
lol look, [there's already one](https://github.com/AEGEE/oms-events/blob/master/.dockerignore)

**Comment by serge1peshcoff** [comment]
lol, I wrote it and forgot about it. and yep, you are right about it not being taken into account

**Comment by serge1peshcoff** [comment]
can you remove the old Dockerfile so there won't be confusion? @linuxbandit

**Comment by linuxbandit** [comment]
I think I wrote it when I tried first time to have it "docker way", but we didn't have production yet so we didn't care as much - do you mean that I should delete Dockerfile.dev?

**Comment by serge1peshcoff** [comment]
the one in docker/oms-events, there are two and it can cause a confusion

**Comment by serge1peshcoff** [comment]
no idea, but approve, if this works for you, you can merge

**Pull request closed without merging**
