### PR TITLE
Sync dev into master?

### PR DESCRIPTION
**Pull request by linuxbandit**
What would be the status of events if `dev` and `master` went into sync?

Would there be more bugs or more stability?

asking because the docker way for production of course assumes that master is stable (not implying it is not - but at the same time it doesn't have travis-ci as of now)

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@linuxbandit I suppose it would be more stable, but I should check it in details to say for sure.

**Comment by linuxbandit** [comment]
Thanks, I asked because for the non-dev version where we don't mount the folder I obtain this when I `docker-compose`:

``` Starting child process with 'node /usr/app/oms-events/lib/server.js'
omsevents_1                 | /usr/app/oms-events/lib/imageserv.js:11
omsevents_1                 | const uploadFolderName = `${config.media_dir}/headimages`;
omsevents_1                 |                                   ^
omsevents_1                 |
omsevents_1                 | TypeError: Cannot read property 'media_dir' of undefined
```

**Comment by serge1peshcoff** [comment]
@linuxbandit yep, most of the things there are refactoring tasks. Also I've changed API slightly, so if we would like this to work, we should make the PR on oms-events-frontend also, otherwise half of the frontend wouldn't work.

**Comment by linuxbandit** [comment]
aha, I see and it makes sense.

All I wanted to do is to raise the question, but for this technicalities you know better - would you be able to take care of it? No time window of course, do it at your earliest availability

**Comment by serge1peshcoff** [comment]
@linuxbandit you mean merge it/make another PR? If so, I can and I'll try to do it ASAP, but I want to set the pipeline on my PC first, because for now my Docker setup isn't working.

**Comment by linuxbandit** [comment]
Yes I meant that

I will write you in private about the pipeline

**Comment by serge1peshcoff** [comment]
Anyway, from what I'm seeing now, it'd became unusable if we'll merge it into master, as it doesn't use oms-serviceregistry and traefik, so there's probably no point in merging it now.
I suggest to refactor oms-events so it would support these features (I'm going to do it in a couple of days) and then merge.
What do you think @linuxbandit @blacksph3re?

**Comment by i3anaan** [comment]
Not a relevant discussion anymore. Will possibly have a similar discussion in the near future, but not right now.

**Pull request closed without merging**
